plugin_blacklist:
- hil
- wheel_odometry
- obstacle_distance
- mount_control
- gps_status
- landing_target
- 3dr_radio
- safety_area
- image_pub
- vibration
# distance_sensor
- actuator_control
- ftp
- cam_imu_sync 
- safety_area
- vfr_hud
- px4flow
- global_position
- local_position
- mocap_pose_estimate
- vision_pose_estimate
- vision_speed_estimate
- waypoint
- local_position
- setpoint_position
- setpoint_accel
- setpoint_attitude
- setpoint_velocity
#- setpoint_raw
- debug_value
- trajectory
- wind_estimation
- timesync_status
- time_reference
- statustext
- rangefinder
- log_transfer
- home_position
- gps_rtk
- fake_gps
- companion_process
- adsb

plugin_whitelist: []
#- 'sys_*'
