is_sim: false # sim: yaw rate cmd, real: conver yaw rate cmd to yaw cmd to send to mavros_control_interface

Kp_x: 2.9 #0.5 #0.12
Kd_x: 2.4 #0.5 #0.005
Ki_x: 0.2
Kp_vel_x: 2.8 #2.4 
Kd_vel_x: 0.0
Ki_vel_x: 1.5 #1.0 #1.0 #2.9
acc_x_max: 3.0
alpha_x: 0.55 #0.5

Kp_y: 2.9 #0.5 #0.12
Kd_y: 2.4 #0.5 #0.005
Ki_y: 0.2
Kp_vel_y: 2.8 #2.4 
Kd_vel_y: 0.0
Ki_vel_y: 1.5 #1.0 #2.9
acc_y_max: 3.0
alpha_y: 0.55 #0.5

Kp_z: 1.5 #1.3 #0.5 #0.05
Kd_z: 0.7 #1.0 #0.7 #0.01
Ki_z: 0.4 #0.0
Kp_vel_z: 2.4 #1.3 
Kd_vel_z: 0.0
Ki_vel_z: 1.4
acc_z_max: 3.0
alpha_z: 0.55 #0.0

antiwindup_radius_pos: [0.2, 0.2, 0.2]
integrator_pos_max: [0.65, 0.65, 0.65]

antiwindup_radius_vel: [0.2, 0.2, 0.4]
integrator_vel_max: [0.65, 0.65, 1.0]

use_vehicle_frame: true # Acceleration command is in vehicle frame (true) or world frame (false)
use_yaw_stabilize: false # true: stabilizes yaw angle around 0 or false: control yaw_rate based on command/rate_thrust -->
K_yaw: 1.8 # used only if use_yaw_stabilize = true
yaw_rate_limit: 80.0 #60.0 # deg/s # used only if use_yaw_stabilize = true

mass: 1.264 #1.244 #1.15 # 1.224
z_static: 1.0 #0.75