is_sim: false # sim: yaw rate cmd, real: conver yaw rate cmd to yaw cmd to send to mavros_control_interface

Kp_x: 2.9 #0.5 #0.12
Kd_x: 2.4 #0.5 #0.005
Ki_x: 0.2
acc_x_max: 2.0
alpha_x: 0.0

Kp_y: 2.9 #0.5 #0.12
Kd_y: 2.4 #0.5 #0.005
Ki_y: 0.2
acc_y_max: 2.0
alpha_y: 0.0

Kp_z: 1.3 #0.5 #0.05
Kd_z: 1.0 #0.7 #0.01
Ki_z: 0.0
acc_z_max: 2.0
alpha_z: 0.0

use_vehicle_frame: true # Acceleration command is in vehicle frame (true) or world frame (false)
use_yaw_stabilize: false # true: stabilizes yaw angle around 0 or false: control yaw_rate based on command/rate_thrust -->
K_yaw: 1.8 # used only if use_yaw_stabilize = true
yaw_rate_limit: 45.0 # deg/s # used only if use_yaw_stabilize = true

mass: 1.1
z_static: 1.0