is_sim: false # sim: yaw rate cmd, real: conver yaw rate cmd to yaw cmd to send to mavros_control_interface

Kp_x: 2.9 #0.5 #0.12
Kd_x: 2.4 #0.5 #0.005
Ki_x: 0.2
Kp_vel_x: 2.4 
Kd_vel_x: 0.0
Ki_vel_x: 1.0 #2.9
acc_x_max: 2.0
alpha_x: 0.5

Kp_y: 2.9 #0.5 #0.12
Kd_y: 2.4 #0.5 #0.005
Ki_y: 0.2
Kp_vel_y: 2.4 
Kd_vel_y: 0.0
Ki_vel_y: 1.0 #2.9
acc_y_max: 2.0
alpha_y: 0.5

Kp_z: 1.5 #1.3 #0.5 #0.05
Kd_z: 1.0 #0.7 #0.01
Ki_z: 0.0 #0.0
Kp_vel_z: 1.0 
Kd_vel_z: 0.0
Ki_vel_z: 1.3
acc_z_max: 2.0
alpha_z: 0.0

use_vehicle_frame: true # Acceleration command is in vehicle frame (true) or world frame (false)
use_yaw_stabilize: false # true: stabilizes yaw angle around 0 or false: control yaw_rate based on command/rate_thrust -->
K_yaw: 1.8 # used only if use_yaw_stabilize = true
yaw_rate_limit: 60.0 # deg/s # used only if use_yaw_stabilize = true

mass: 1.224 #1.15 # 1.224
z_static: 1.0